# These are supported funding model platforms

github: # Replace with your username if you want sponsorships
  - DLinacre

# patreon: # Replace with a patreon username
# open_collective: # Replace with a username
# ko_fi: # Replace with a username
# tidelift: # Replace with a platform-specific account
# community_bridge: # Replace with a platform-specific account
# liberapay: # Replace with a username
# issuehunt: # Replace with a username
# lfx_crowdfunding: # Replace with a username
# polar: # Replace with a username
# buy_me_a_coffee: # Replace with a username
# custom: ['https://linacre.site'] # or your own site
